site_name: CIEE

theme:
  name: material
  language: pt
  logo: img/logowhite.png
  favicon: img/logo.png
  palette:
    scheme: slate

nav:
  - Inicio: index.md
  - Planejamento:
    - Escolha do site: planejamento/escolha_site.md
    - Ferramentas: planejamento/ferramentas.md
    - Cronograma: planejamento/cronograma.md
    - Processo de Design: planejamento/processo.md
  - Análise de Requisitos:
    - Perfil de Usuário: analise_requisitos/perfil_usuario.md
    - Aspectos Éticos: analise_requisitos/aspectos_eticos.md
    - Personas: analise_requisitos/personas.md
    - Análise de Tarefas: analise_requisitos/analise_tarefas.md
    - Princípios Gerais do Projeto: analise_requisitos/Principios_projeto.md
    - Metas de Usabilidade: analise_requisitos/metas_usabilidade.md
    - Guia de Estilo: analise_requisitos/guia_estilo.md
  - Apresentações: apresentacoes.md
